INSERT INTO RATING VALUES (1, 'G');
INSERT INTO RATING VALUES (2, 'PG');
INSERT INTO RATING VALUES (3, 'PG-13');
INSERT INTO RATING VALUES (4, 'R');
INSERT INTO RATING VALUES (5, 'NC-17');

-- INSERT INTO FILM VALUES (1, 'Гарри Поттер 1', 'Про мальчика волшебника Гарри', '2002-03-21', 150, 1);
-- INSERT INTO FILM VALUES (2, 'Гарри Поттер 2', 'Про мальчика волшебника Гарри', '2002-11-03', 150, 2);
-- INSERT INTO FILM VALUES (3, 'Гарри Поттер 3', 'Про мальчика волшебника Гарри', '2004-05-31', 150, 2);
-- INSERT INTO FILM VALUES (4, 'Гарри Поттер 4', 'Про мальчика волшебника Гарри', '2005-12-22', 150, 2);
-- INSERT INTO FILM VALUES (5, 'Гарри Поттер 5', 'Про мальчика волшебника Гарри', '2008-06-28', 150, 2);
--
INSERT INTO GENRE VALUES (1, 'Комедия');
INSERT INTO GENRE VALUES (2, 'Драма');
INSERT INTO GENRE VALUES (3, 'Мультфильм');
INSERT INTO GENRE VALUES (4, 'Триллер');
INSERT INTO GENRE VALUES (5, 'Документальный');
INSERT INTO GENRE VALUES (6, 'Боевик');
--
-- INSERT INTO FILM_GENRE VALUES (1, 1);
-- INSERT INTO FILM_GENRE VALUES (2, 1);
-- INSERT INTO FILM_GENRE VALUES (2, 2);
-- INSERT INTO FILM_GENRE VALUES (3, 4);
-- INSERT INTO FILM_GENRE VALUES (3, 2);
-- INSERT INTO FILM_GENRE VALUES (3, 1);
-- INSERT INTO FILM_GENRE VALUES (4, 2);
-- INSERT INTO FILM_GENRE VALUES (5, 6);
--
-- INSERT INTO USERS VALUES (1, 'masha@mail.ru', 'Mashanya', 'Маша Петрова', '2000-12-23');
-- INSERT INTO USERS VALUES (2, 'dasha@mail.ru', 'Dashanya', 'Даша Иванова', '2001-08-15');
-- INSERT INTO USERS VALUES (3, 'petya@mail.ru', 'Petunya', 'Петя Васильев', '1999-06-08');
-- INSERT INTO USERS VALUES (4, 'gosha@mail.ru', 'Goshan', 'Гоша Булочкин', '2000-10-14');
-- INSERT INTO USERS VALUES (5, 'zina@mail.ru', 'Zinaida', 'Зина Сидорова', '2005-05-26');
--
-- INSERT INTO USERS_FRIEND VALUES (1, 2, FALSE);
-- INSERT INTO USERS_FRIEND VALUES (2, 1, TRUE);
-- INSERT INTO USERS_FRIEND VALUES (3, 1, FALSE);
-- INSERT INTO USERS_FRIEND VALUES (1, 3, TRUE);
-- INSERT INTO USERS_FRIEND VALUES (3, 2, FALSE);
-- INSERT INTO USERS_FRIEND VALUES (2, 3, TRUE);
-- INSERT INTO USERS_FRIEND VALUES (4, 5, FALSE);
-- INSERT INTO USERS_FRIEND VALUES (5, 4, TRUE);
--
-- INSERT INTO LIKES VALUES (1, 1);
-- INSERT INTO LIKES VALUES (2, 1);
-- INSERT INTO LIKES VALUES (3, 1);
-- INSERT INTO LIKES VALUES (4, 2);
-- INSERT INTO LIKES VALUES (5, 3);
-- INSERT INTO LIKES VALUES (5, 1);

